name: portfolio_clean
description: Hi, am a mobile application developer with experience in developing applications for both iOS and Android platforms. I have experience in developing applications using Flutter(Dart), Java, and Kotlin programming languages. I am passionate about creating user-friendly applications that provide a seamless user experience. I am also experienced in working with teams and collaborating with designers to create visually appealing applications.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.9
  flutter_native_splash: ^2.2.17
  carousel_slider:
  dots_indicator:

flutter_native_splash:
  color: "#121212"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          style: normal
          weight: 700

